Filmlist and adapter 2
wobl9/learningAndroid pull request #3
Opened 2021-12-18 06:33 UTC by MarinaRomanovna

По максимуму исправила замечания. Нужно как-то менять список в адаптере, не теряя старые данные. То есть, если у нас меняется коллекция, нужно чтобы метод в адаптере сохранил там и старые данные и новые, да?
По FilmDetail:
- Пока просто проверила, передалось ли у нас айди в сам фрагмент.
- Что делать во вью модели? Нужно создать метод, который берет данные из репозитория по номеру айди? Далее подписаться на данные этого метода и уже во фрагменте установить слушателя? Просто на данном этапе немного не понимаю, как реализовать вью модель. Нужно ли также, как в списке фильмов делать фабрику?

2021-12-19 15:15 UTC, wobl9 requested changes

2021-12-19 15:15 UTC, wobl9 commented on app/build.gradle
> +    implementation 'io.cabriole:decorator:1.3.0'
от этого избавляемся, это не нужно

2021-12-19 15:15 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/filmdetail/FilmDetailFragment.kt
> +private const val ARGS_FILM_ID = "film_id"
в companion object убирай, и делай публичным внутри. тогда можно будет обратившись к фрагменту понять какие аргументы ему можно передать

2021-12-19 15:15 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/filmdetail/FilmDetailFragment.kt
> +        }
молодец, хорошее решение. попробуй еще экстеншн написать, чтобы этот код не дублировать в каждом фрагменте

2021-12-19 15:15 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/filmslist/FilmsFragment.kt
> +    interface Callbacks {
Дай название более осознанное. А то непонятно что за колбек

2021-12-19 15:15 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/filmdetail/FilmDetailFragment.kt
> +        //_binding = FilmDetailFragmentBinding.bind(view)
с этим надо разобраться, так не должно быть

2021-12-19 15:15 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/filmslist/FilmsFragment.kt
> +            context?.resources?.getDimensionPixelSize(R.dimen.left_right_margin)!!,
используй requireContext()

2021-12-19 15:15 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/filmslist/FilmsAdapter.kt
> +            }
передавай в адаптер колбек через интерфейс. не факт, что у тебя будет колбек реализовываться кем-то. или на крайний случай используй as?

2021-12-19 15:15 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/filmslist/FilmsAdapter.kt
> +    private var filmsList: List<FilmModel> = mutableListOf()
почему mutableList? ты же никак его не изменяешь

2021-12-19 15:15 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/filmslist/FilmsAdapter.kt
> +        }
смысл тут мапить? можно же просто новый список присвоить filmsList

2021-12-19 15:15 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/filmslist/FilmsFragment.kt
> +        decorateRecyclerView()
при каждом изменении списка ты будешь снова устанавливать layoutManager и декоратор. Вынеси это отсюда. Достаточно один раз

2021-12-19 15:15 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/filmslist/FilmsFragment.kt
> +        }
создай sealed class State в котором будет 3 наследника: Loading, Content(items: List<FilmModel>) и Error. Во вьюмодели напиши логику которая будет по данным определять стейт и передавай во фрагмент. Здесь у тебя будет конструкция
```
when(state) {} 
```
и по ней пройдешься по стейтам

2021-12-19 15:15 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/mainactivity/MainActivity.kt
> +    }
это колбек лучше реализовать во фрагменте со списком. Потому что активити ничего не знает о списке фильмов. Оно должно реализовать другой колбек, который будет сменять экран.

2021-12-19 15:15 UTC, wobl9 commented on app/src/main/res/layout/list_item_film.xml
> +    android:background="@color/black">
можно без него, просто картинку оставить

2022-01-29 20:16 UTC, wobl9 commented on app/src/main/res/values/strings.xml
> +    <string name="overview">Film\'s overview</string>
давай на русском приложение делать

2022-01-29 20:26 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/filmslist/adapter/FilmsAdapter.kt
> +    var onFilmItemClickListener: ((FilmModel) -> Unit)? = null
пока можно оставить так, но лучше передавать прям во вьюхолдер

2022-01-29 20:28 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/filmslist/FilmsFragment.kt
> +                .commit()
нет, делай через колбек. Создавай интерфейс и к родители обращайся по интерфейсу и пусть он определяет что делать

2022-01-29 20:29 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/filmslist/FilmsFragment.kt
> +            emptyList.visibility = View.INVISIBLE
видимость должна только от стейта определятся. начальную видимость можно в верстке задать

2022-01-29 20:35 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/filmslist/FilmsFragment.kt
> +        adapter.submitList(list)
адаптер создается на каждый успешный стейт, не надо так

2022-01-29 20:41 UTC, wobl9 requested changes

2022-01-29 20:41 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/filmslist/FilmsFragment.kt
> +                is BaseViewState.Success<*> ->
укажи тип, ты же знаешь какой он

2022-01-29 20:41 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/filmdetail/FilmDetailViewModel.kt
> +        getFilmsUseCase.execute(1, FilmsLanguage.RUS)
что такое 1? вынеси в константы

2022-01-29 20:41 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/filmdetail/FilmDetailFragment.kt
> +            filmOverview.text = filmModel.overview
есть экстеншн у вью View.isVisible можешь его использовать

2022-01-29 20:41 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/filmdetail/FilmDetailFragment.kt
> +    private fun initializeView(filmModel: FilmModel) {
по названию это метод инициализации, но по факту это метод который отображает успешный стейт. поменяй нейминг

2022-01-30 10:55 UTC, wobl9 commented
нужно передавать модель фильма на фрагмент с деталями, нет смысла запрашивать два раза

2022-02-02 11:38 UTC, MarinaRomanovna commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/filmslist/FilmsFragment.kt
> +                is BaseViewState.Success<*> ->
При указании типа студия ругается и предлагает заменить на <*>. Предполагаю, это из-за того, что в BaseViewState.Success задан любой тип данных на входе.

2022-02-04 17:24 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/mainactivity/MainActivity.kt
> +        supportActionBar?.hide()
это зачем?

2022-02-04 17:25 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/filmslist/adapter/FilmsAdapter.kt
> +    var onFilmItemClickListener: ((FilmModel) -> Unit)? = null
почему не убрала? и зарезолвила

2022-02-07 16:32 UTC, MarinaRomanovna commented on app/src/main/java/ru/wobcorp/justforpractice/data/repositories/FilmsRepository.kt
> +}
Сейчас этот код немного не работает, т.к. в Сингл может лежать только не нулабельный объект. Посмотри, пожалуйста, этот момент. Логика хотя бы такая?

2022-02-07 19:28 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/filmslist/FilmsFragment.kt
> +                is BaseViewState.Success<*> ->
добавь потом todo, надо будет глянуть

2022-02-07 19:40 UTC, wobl9 requested changes
попробуй накидать несколько вариантов нашей схемы, не без коммита. покодим вместе на выходны
![640x800_e566d330-2b86-42e8-a79e-1ac336b2bb57](https://user-images.githubusercontent.com/46030646/152859939-66165082-1823-4607-bfa6-75dd013cbd73.jpg)
х

2022-02-07 19:40 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/data/repositories/FilmsRepository.kt
> +    }
удали это, вместе напишем код

2022-02-07 19:40 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/domain/models/FilmsSourceModel.kt
> +        }
тоже удаляй

2022-02-07 19:40 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/filmdetail/FilmDetailFragment.kt
> +        filmId = arguments?.getInt(ARGS_FILM_ID) as Int
а если аргументов не будет, то упадем

2022-02-07 19:40 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/filmdetail/FilmDetailFragment.kt
> +            return FilmDetailFragment().putArguments(ARGS_FILM_ID, filmId) as FilmDetailFragment
зачем кастить к фрагменту? Функция и так возвращает фрагмент нужного типа

2022-02-07 19:40 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/filmdetail/FilmDetailFragment.kt
> +                is BaseViewState.Error -> initializeEmptyView()
нейминг не поправила

2022-02-07 19:40 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/filmdetail/FilmDetailViewModel.kt
> +                _state.value = BaseViewState.Success(it)
почему загрузку не обрабатываешь? вдруг его нету в кэше

2022-02-07 19:40 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/filmslist/FilmsFragment.kt
> +            renderingState(it)
название неудачное. У тебя существительное получилось а должно быть действие

2022-02-07 19:40 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/filmslist/FilmsFragment.kt
> +            }
оставляй todo

2022-02-07 19:40 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/filmslist/FilmsViewModel.kt
> +                }
тоже загрузки нету

2022-02-07 19:40 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/filmslist/adapter/FilmsAdapter.kt
> +    var onFilmItemClickListener: ((FilmModel) -> Unit)? = null
в чем проблема? почему это тут живет до сих пор?

2022-02-07 19:40 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/mainactivity/MainActivity.kt
> +            FilmDetailFragment.newInstance(filmId))
форматирование сделай

2022-02-20 10:17 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/data/repositories/FilmsRepository.kt
> +    private val filmsDataStore: FilmsDataStore = FilmsDataStore.getInstance()
так нельзя делать, у тебя все зависимости должны через даггер собираться

2022-02-20 10:18 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/data/stores/FilmsDataStore.kt
> +    }
это все не нужно

2022-02-20 10:19 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/data/stores/FilmsDataStore.kt
> +class FilmsDataStore @Inject constructor() {
чтобы объект был синглтоном надо пометить его квалифаером и тогда даггер в рамках одного компонента будет создавать только один инстанс

2022-02-20 10:19 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/data/stores/FilmsDataStore.kt
> +    private val lock = ReentrantReadWriteLock()
достаточно одной синхронизации

2022-02-20 10:22 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/filmdetail/FilmDetailFragment.kt
> -        filmId = arguments?.getInt(ARGS_FILM_ID) as Int
эта строчка была нормальной, только надо было в ней обработать ошибку
```
filmId = requireNotNull(arguments?.getInt(ARGS_FILM_ID) as? Int) { "cannot start fragment without id "} 
```

2022-02-20 10:23 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/filmdetail/FilmDetailViewModel.kt
> +                },
при ошибке будет загрузка

2022-02-20 10:23 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/filmdetail/FilmDetailViewModel.kt
> +                },
покажи кнопку повторить

2022-02-20 10:23 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/filmslist/FilmsComponent.kt
> +    }
расскажу как без модуля сделать

2022-02-20 10:26 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/filmslist/FilmsFragment.kt
> +                filmDetailLauncher.launchFilmDetail(filmId)
передай лямбду во внутрь

2022-02-20 10:27 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/filmslist/FilmsFragment.kt
> +                bindErrorRendering()
почему bind?

2022-02-20 10:28 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/filmslist/adapter/FilmsAdapter.kt
>  class FilmsAdapter : ListAdapter<FilmModel, FilmHolder>(FilmDiffUtilCallback()) {
прям в конструктор передай кликлистенер и потом во вьюхолдер

2022-03-05 21:55 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/filmslist/FilmsFragment.kt
> +        (requireActivity() as FilmDetailLauncher).launchFilmDetail(filmId)
лучше через нулабельность, безопаснее будет  requireActivity() as? FilmDetailLauncher

2022-03-05 21:58 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/login/fragment/LoginViewModel.kt
> +    }
можно compain сделать приватным вместо того чтобы все переменные делать приватными

2022-03-05 21:59 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/login/fragment/LoginViewModel.kt
> +    }
почему функция называется parseLogin?

2022-03-05 22:00 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/login/fragment/LoginViewModel.kt
> +        }
не нужен никакой catch, просто ограничь ввод текста только цифраами

2022-03-05 22:00 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/login/fragment/LoginViewModel.kt
> +        }
напиши useCase который будет это делать

2022-03-05 22:01 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/login/fragment/LoginFragment.kt
> +        })
поищи мб есть экстенш который реагирует только на onTextChanged или напиши сама

2022-03-05 22:01 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/login/fragment/LoginFragment.kt
> +        sharedPrefHelper.put(IS_LOGIN, true)
во вьюмодели надо делать

2022-03-05 22:02 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/login/fragment/LoginFragment.kt
> +        }
тоже логи вьюмодели

2022-03-05 22:03 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/login/fragment/LoginFragment.kt
> +                val isFieldsValid = viewModel.checkUserData(login, password)
нет, это отвратилеьно и неправильно. не должно быть методов во вьюмодели которые возвращают результат

2022-03-05 22:04 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/login/fragment/LoginFragment.kt
> +            } else null
если используешь {} в if, то в esles тоже используй. либо если помещается можно в одну строку и тогда без скобок

2022-03-05 22:04 UTC, wobl9 commented on app/src/main/java/ru/wobcorp/justforpractice/presentation/login/fragment/LoginFragment.kt
> +        viewModel.errorInputLogin.observe(lifecycleScope) {
именуй анонимные параметры

2022-03-05 22:11 UTC, wobl9 commented on app/src/main/res/layout/film_detail_fragment.xml
> +    </ScrollView>
это странная штука какая-то

2022-03-05 22:13 UTC, wobl9 approved these changes
дабы пул реквест не был в один миллион строк, я замержу, потом отдельным правки добьем

2022-03-05 22:13 UTC, merged